name: masala_box
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.2
  get: ^4.6.5
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  riverpod_annotation: ^2.1.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  riverpod_generator: ^2.2.3
  mockito: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  build_runner: ^2.4.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/data.json

scripts:
  watch: dart run build_runner watch --delete-conflicting-outputs
